weird_exit: mwe_weird_exit.cpp
	g++ -O0 mwe_weird_exit.cpp -o weird_exit
	./weird_exit
	rm weird_exit

circus_tower: circus_tower.cpp
	g++ -std=c++17 circus_tower.cpp -o circus_tower
	./circus_tower
	rm circus_tower
